project_id = "testproject-438104"
region = "us-central1"
container_image = "us-central1-docker.pkg.dev/testproject-438104/docker0images/weather-app:latest"
service_name = "mcd-cloud-run"
invoker_identity = "serviceAccount:concomm@testproject-438104.iam.gserviceaccount.com"
credentials_file = "sa_cred.json"